<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"[]>
<plist version="1.0">
  <!-- Generated via. Iro4CLI -->
  <dict>
    <key>fileTypes</key>
    <array>
      <string>jvc</string>
    </array>
    <key>name</key>
    <string>JuvixCore</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.JuvixCore</string>
    <key>uuid</key>
    <string></string>
    <key>repository</key>
    <dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#block_comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line_comment</string>
          </dict>
        </array>
      </dict>
      <key>line_comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(--)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.JuvixCore</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.JuvixCore</string>
            <key>end</key>
            <string>($)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.JuvixCore</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>block_comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\\{-)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.JuvixCore</string>
              </dict>
            </dict>
            <key>contentName</key>
            <string>comment.JuvixCore</string>
            <key>end</key>
            <string>(-\\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>comment.JuvixCore</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>